package org.kobjects.kowa.core.module

enum class Extension {
    BULK_MEMORY_OPERATIONS,
    EXTENDED_CONSTANT_EXPRESSIONS,
    GARBAGE_COLLECTION,
    MULTIPLE_MEMORIES,
    MULTIVALUE,
    REFERENCE_TYPES,
    RELAXED_SIMD,
    NON_TRAPPING_FLOAT_TO_INT_CONVERSIONS,
    SIGN_EXTENSION_OPERATIONS,
    FIXED_WIDTH_SIMD,
    TAIL_CALLS,
    THREADS,
    EXCEPTION_HANDLING,
    MEMORY_64,
    TYPE_REFLECTION,

    GC_DEVELOPMENT,
}